name: Build and push Docker image 'pyenv_python'

on:
  push:
    branches:
      - master
    paths:
      - 'pyenv_python/**'
      - '.github/workflows/build_image_pyenv_python.yml'

  pull_request:
    paths:
      - 'pyenv_python/**'
      - '.github/workflows/build_image_pyenv_python.yml'

env:
  IMAGE_DIR: ./pyenv_python
  IMAGE_NAME: ghcr.io/${{ github.repository }}/pyenv_python
  IMAGE_TAG: v1
  IMAGE_ARCHS: linux/amd64,linux/arm,linux/arm64

jobs:
  create-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GHRC
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Build and Load
        uses: docker/build-push-action@v2
        with:
          context: ${{env.IMAGE_DIR}}
          platforms: ${{env.IMAGE_ARCHS}}
          tags: ${{env.IMAGE_NAME}}:${{env.IMAGE_TAG}}

      - name: Test Image
        run: docker run --rm ${{env.IMAGE_NAME}}:${{env.IMAGE_TAG}}

      # Push only when merged to master; cached form 'Build and Load' step
      - name: Build and Push
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: docker/build-push-action@v2
        with:
          context: ${{env.IMAGE_DIR}}
          platforms: ${{env.IMAGE_ARCHS}}
          push: true
          tags: ${{env.IMAGE_NAME}}:${{env.IMAGE_TAG}}
